name: normal

on:
  push:
    branches:
      - master

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build x86 image
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ehco1996/v2scar
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest"
          dockerfile: Dockerfile